### ISSUE TITLE
Add ability to press `Tab` to cycle through the tabs

### ISSUE THREAD

**Issue by sindresorhus** [jdeniau/ink-tab#1]
And when it's at the end, it should go back to the beginning.

**Comment by jdeniau** [comment]
You are right, it will be closer to other programs.

Will implement it opefully tomorrow

**Comment by sindresorhus** [comment]
I would also like to see support for Shift+Tab to cycle backwards.

**Comment by jdeniau** [comment]
Yes, I will try it too.

I'm thinking about direct access to a tab number but maybe harder to implement without conflicting with app or tmux. 
Maybe with something like g-<tab number>

**Comment by sindresorhus** [comment]
Hmm, maybe Option+Tab then.

---

> Maybe with something like g-<tab number>

I think that could be a useful addition, but I personally prefer to just cycle through tabs.

**Comment by jdeniau** [comment]
Done in v1.1.0.

Thanks for all the open-source work you done by the way :+1:
