### ISSUE TITLE
how to pass focus into child components and go back up from child components to tabs

### ISSUE THREAD

**Issue by sw-yx** [jdeniau/ink-tab#14]
lets say i want to combine ink-tab with ink-text-input - so i can tab through some pages, go in and type a form, and tab out. what are your thoughts on how this can be done? i dont seem able to escape the text input in this example:

```tsx
import { Command, flags } from '@oclif/command';

import React from 'react';
import { render, Box, Static, Color } from 'ink';
import TextInput from 'ink-text-input';
// @ts-ignore - ts cant find our ambient module declaration
import { Tabs, Tab } from 'ink-tab';

function SearchQuery({ placeholder }: { placeholder: string }) {
  const [activeTab, setActiveTab] = React.useState(null);
  const [query, setQuery] = React.useState('');
  const [entries, setEntries] = React.useState<string[]>([]);

  const handleSubmit = (query: string) => {
    // Do something with query
    setEntries([...entries, query]);
    setQuery('');
  };

  return (
    <Box flexDirection="column">
      <Box>
        {activeTab === 'foo' && 'Selected tab is "foo"'}
        {activeTab === 'bar' && 'Selected tab is "bar"'}
        {activeTab === 'baz' && 'Selected tab is "baz"'}
      </Box>
      <Box marginRight={1}>Enter your query:</Box>
      <TextInput
        value={query}
        onChange={setQuery}
        onSubmit={handleSubmit}
        placeholder={placeholder}
      />
      <Static>
        {entries.map((entry, id) => (
          <Box key={id}>{entry}</Box>
        ))}
      </Static>
      <Tabs onChange={(x: any) => setActiveTab(x)}>
        <Tab name="foo">Foo</Tab>
        <Tab name="bar">Bar</Tab>
        <Tab name="baz">Baz</Tab>
      </Tabs>
    </Box>
  );
}

export default class Stream extends Command {
  static description = 'describe the command here';
  async run() {
    const { args, flags } = this.parse(Stream);

    const app = render(
      <SearchQuery placeholder={flags.placeholder || 'Counter'} />
    );
  }
}

```

**Comment by jdeniau** [comment]
Hi, 

I tried your example, and it does work, except the fact that when you press left arrow, the cursor does move in the input, and changes the tab.

The probable "UX-friendly" solution is to manage where your cursor is:

* If you decide to navigate through tabs, you should not have the text-input available
* If you are in an input, then the tab component should not respond

But there is a missing key here : If I'm right, we do not know which element has the focus, and neither `ink-tab` nor `ink-text-input` implement a way of disable input for now.

The solution I see : 

- Implement a `isInputHandled: bool` on each component, and manage the focus in you app, but it will be only a local solution and all implementation may differ.
- Provide a global solution in `ink`, but it could be hard to implement.

Maybe @vadimdemedes have a vision here on a future implementation here ?

PS: there is a dirty solution as `ink-text-input` does not respond on ARROW_UP and ARROW_DOWN events: you can set `<Tabs flexDirection="column">`. it will change your tab layout, but `ink-tab` will respond to ARROW_UP / ARROW_DOWN and `ink-text-input` will not.
I said it was dirty 😉

**Comment by sw-yx** [comment]
dirty!!

anyway, i know this is an unexamined topic.. but i figured its important to understand which element has focus. may even want to implement a simple "focus ring" to show which element has focus!

**Comment by jdeniau** [comment]
Let's see what does pops out of vadimdemedes/ink#242  about that. As soon as there is something, I will update ink-tab to work with it.

**Comment by jdeniau** [comment]
For the record I opened https://github.com/vadimdemedes/ink/pull/262 on ink that should handle focus.

**Comment by jdeniau** [comment]
In the same time, I released a version of `ink-tab` that supports the `hasFocus` prop.

I suggest you to wait until ink manages focus globally, but you can play with it if you'd like.

See https://github.com/jdeniau/ink-tab#focus-management if you want to know more.

**Comment by jdeniau** [comment]
This feature is now available in ink 3.x using ink-tab 4.x.

See [ink documentation](https://github.com/vadimdemedes/ink#usefocusoptions) and [ink-tab documentation](https://jdeniau.gitbook.io/ink-tab/api/tabs#focus-management)
