### ISSUE TITLE
Fails to compile when using typescript

### ISSUE THREAD

**Issue by philipp-cloudproduce** [jdeniau/ink-tab#23]
When I put your foo,bar,baz tabs example into my tsx I received the following error:

src/index.tsx:128:17 - error TS2605: JSX element type 'ReactNode' is not a constructor function for JSX elements.
  Type 'string' is not assignable to type 'Element'.

128                 <Tab name="foo">Foo</Tab>

Here is the offending snippet of my code in side a vanilla class component:

```js
render() {
    return (
      <Box>
        <Tabs onChange={this.handleTabChange}>
          <Tab name="foo">Foo</Tab>
          <Tab name="bar">Bar</Tab>
          <Tab name="baz">Baz</Tab>
        </Tabs>
        {this.state.activeTab === 'foo' && 'Selected tab is "foo"'}
        {this.state.activeTab === 'bar' && 'Selected tab is "bar"'}
        {this.state.activeTab === 'baz' && 'Selected tab is "baz"'}
      </Box>
    );
}
```

**Comment by jdeniau** [comment]
Thanks :+1: 

This should be fixed in 3.0.2

As I am not really used to typescript, feel free to reopen the issue if the bug i still occuring.
