### ISSUE TITLE
Cannot read property of 'Consumer' of undefined

### ISSUE THREAD

**Issue by rharkov** [jdeniau/ink-tab#26]
Hey, doing project with ink and have issue with using ink-tabs. 
Attaching two screenshots on whats going on, if you need more info let me know!
# #
<img width="775" alt="Screen Shot 2020-08-23 at 10 11 26 PM" src="https://user-images.githubusercontent.com/47150563/91000615-915f8480-e597-11ea-8813-7c55569b608d.png">
<img width="524" alt="Screen Shot 2020-08-23 at 10 45 55 PM" src="https://user-images.githubusercontent.com/47150563/91000618-93c1de80-e597-11ea-90af-4a2b3dfcf121.png">

Thanks!

**Comment by jdeniau** [comment]
Hi,

This is probably a problem with the version on ink that you use.

Can you tell me which version of ink and ink tab you are using?

**Comment by rharkov** [comment]
we are using 3.0.4 for ink and 3.0.2 for ink tab

**Comment by jdeniau** [comment]
OK, that is probably due to ink 3.
The peerDep is `^2.2.0`, and IIRC ink 3 did changes some stuff with the contexts.

I will try to update ink-tab for ink 3 soon (or if you want to open a PR, it's great !)

**Comment by rharkov** [comment]
Thanks! we are trying ink-select-input now. We really want this project to work but we keep hitting so many walls on the way and unfortunately not a lot of examples or help online. We cannot even get basic example to run :(

**Comment by rharkov** [comment]
Maybe you have some sort of faster communication way which would help a lot to ask questions and would be easier than asynchronous issues which might be a lot of them as issues are almost on every step with versions and etc.  :(

**Comment by jdeniau** [comment]
It should be fixed with the version [4.0.0](https://github.com/jdeniau/ink-tab/blob/master/CHANGELOG.md#400)

For ink-select-input, you should probably open an issue there. There are [some issue about the bundling though](https://github.com/vadimdemedes/ink-select-input/issues/24)
