### ISSUE TITLE
Peer dependency issue when using ink@4.1.0 at root project

### ISSUE THREAD

**Issue by kasra0** [jdeniau/ink-tab#50]
Hi,
My root project uses ink@4.1.0,
when I do `npm i ink-tab `
I 've got : 

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: my-proj@1.0.0
npm ERR! Found: ink@4.1.0
npm ERR! node_modules/ink
npm ERR!   ink@"^4.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer ink@"^3.0.0" from ink-tab@4.3.1
npm ERR! node_modules/ink-tab
npm ERR!   ink-tab@"*" from the root project

Is it possible to upgrade the dependency to  ink@"^4.1.0" ?

FYI, I copied and pasted the [index.tsx](https://github.com/jdeniau/ink-tab/blob/main/src/index.tsx) to my project and everything was OK with : 

    "ink": "^4.1.0",
    "react": "^18.2.0"

Thanks.

**Comment by jdeniau** [comment]
Great!
I didn't know that ink 4 was out!
You are right, it should work, and should not be a problem I think (peerDeps emit only a warning if I remember correctly).

I will test and publish a new version that accept both ink 3 and 4 soon.

**Comment by kasra0** [comment]
merci ;-)

**Comment by jdeniau** [comment]
Published as [v5.0.0](https://github.com/jdeniau/ink-tab/blob/main/CHANGELOG.md#500).

I published as I upgraded all dev dependencies too (typescript and co), but there should be no breaking change if you are already on ink 4.
